# conda env create -f environment.yml
name: rooki
channels:
  - conda-forge
  - defaults
dependencies:
  # - pip
  #- openssl
  - birdy
  - beautifulsoup4
  - pymetalink
  # open xarray results
  - netcdf4
  - xarray>=0.16
  # esgf search
  - esgf-pyclient
  # intake catalog
  - intake
  - pandas
  - requests
  - aiohttp
  # tests
  #- pytest
  #- flake8
  #- pip:
  #  - -e git+https://github.com/metalink-dev/pymetalink.git@master#egg=metalink
